name = "Multroot"
uuid = "be4981a1-4796-4781-ad4b-2b9bab054ce3"
authors = ["Klaus Crusius <klaus.crusius@web.de>"]
version = "0.1.0"

[compat]
julia = "1"

[deps]
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
